var Module = function(Module) {
  Module = Module || {};

var d;d||(d=typeof Module !== 'undefined' ? Module : {});var aa={},n;for(n in d)d.hasOwnProperty(n)&&(aa[n]=d[n]);d.arguments=[];d.thisProgram="./this.program";d.quit=function(a,b){throw b;};d.preRun=[];d.postRun=[];var q=!1,r=!1,ba=!1,ca=!1;
if(d.ENVIRONMENT)if("WEB"===d.ENVIRONMENT)q=!0;else if("WORKER"===d.ENVIRONMENT)r=!0;else if("NODE"===d.ENVIRONMENT)ba=!0;else if("SHELL"===d.ENVIRONMENT)ca=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else q="object"===typeof window,r="function"===typeof importScripts,ba="object"===typeof process&&"function"===typeof require&&!q&&!r,ca=!q&&!ba&&!r;
if(ba){var da,ea;d.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};d.readBinary=function(a){a=d.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(d.thisProgram=process.argv[1].replace(/\\/g,"/"));d.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;});process.on("unhandledRejection",function(){process.exit(1)});d.inspect=
function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(d.read=function(a){return read(a)}),d.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?d.arguments=scriptArgs:"undefined"!=typeof arguments&&(d.arguments=arguments),"function"===typeof quit&&(d.quit=function(a){quit(a)});else if(q||r)d.read=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},r&&(d.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),d.readAsync=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},d.setWindowTitle=function(a){document.title=a};
d.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;d.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||d.print;d.print=d.print;d.printErr=d.printErr;for(n in aa)aa.hasOwnProperty(n)&&(d[n]=aa[n]);aa=void 0;function ha(a){assert(!ia);var b=t;t=t+a+15&-16;return b}function ja(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ka=0;function assert(a,b){a||u("Assertion failed: "+b)}
function la(a){var b;if(0===b||!a)return"";for(var c=0,e,f=0;;){e=v[a+f>>0];c|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,v.subarray(a,a+Math.min(b,1024))),e=e?e+c:c,a+=1024,b-=1024;return e}return ma(a)}var na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&na)return na.decode(a.subarray(b,c));for(c="";;){var e=a[b++];if(!e)return c;if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|h;else{var g=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|h<<6|g;else{var k=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|h<<12|g<<6|k;else{var l=a[b++]&63;e=(e&1)<<30|f<<24|h<<18|g<<12|k<<6|l}}}65536>e?c+=String.fromCharCode(e):(e-=
65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}}function ma(a){return oa(v,a)}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function pa(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,x,v,qa,ra,y,z,sa,ta;
function ua(){d.HEAP8=x=new Int8Array(buffer);d.HEAP16=qa=new Int16Array(buffer);d.HEAP32=y=new Int32Array(buffer);d.HEAPU8=v=new Uint8Array(buffer);d.HEAPU16=ra=new Uint16Array(buffer);d.HEAPU32=z=new Uint32Array(buffer);d.HEAPF32=sa=new Float32Array(buffer);d.HEAPF64=ta=new Float64Array(buffer)}var va,t,ia,wa,xa,ya,za,A;va=t=wa=xa=ya=za=A=0;ia=!1;
d.reallocBuffer||(d.reallocBuffer=function(a){try{if(ArrayBuffer.fa)var b=ArrayBuffer.fa(buffer,a);else{var c=x;b=new ArrayBuffer(a);(new Int8Array(b)).set(c)}}catch(e){return!1}return Aa(b)?b:!1});var Ba;try{Ba=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Ba(new ArrayBuffer(4))}catch(a){Ba=function(b){return b.byteLength}}var Ca=d.TOTAL_STACK||5242880,B=d.TOTAL_MEMORY||16777216;
B<Ca&&d.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+B+"! (TOTAL_STACK="+Ca+")");d.buffer?buffer=d.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(d.wasmMemory=new WebAssembly.Memory({initial:B/65536}),buffer=d.wasmMemory.buffer):buffer=new ArrayBuffer(B),d.buffer=buffer);ua();y[0]=1668509029;qa[1]=25459;if(115!==v[2]||99!==v[3])throw"Runtime error: expected the system to be little-endian!";
function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.C;"number"===typeof c?void 0===b.H?d.dynCall_v(c):d.dynCall_vi(c,b.H):c(void 0===b.H?null:b.H)}}}var Ea=[],Fa=[],Ga=[],Ha=[],Ia=[],Ja=!1;function Ka(){var a=d.preRun.shift();Ea.unshift(a)}var D=0,La=null,Ma=null;d.preloadedImages={};d.preloadedAudios={};
function Na(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(d.wasmBinary)return new Uint8Array(d.wasmBinary);if(d.readBinary)return d.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(p){u(p)}}function b(){return d.wasmBinary||!q&&!r||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){k=a.exports;if(k.memory){a=k.memory;var b=d.buffer;a.byteLength<b.byteLength&&d.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);d.buffer=buffer=a;ua()}d.asm=k;d.usingWasm=!0;D--;d.monitorRunDependencies&&d.monitorRunDependencies(D);0==D&&(null!==La&&(clearInterval(La),La=null),Ma&&(a=Ma,Ma=null,a()))}
function e(a){c(a.instance)}function h(a){b().then(function(a){return WebAssembly.instantiate(a,g)}).then(a).catch(function(a){d.printErr("failed to asynchronously prepare wasm: "+a);u(a)})}if("object"!==typeof WebAssembly)return d.printErr("no native wasm support detected"),!1;if(!(d.wasmMemory instanceof WebAssembly.Memory))return d.printErr("no native wasm Memory in use"),!1;a.memory=d.wasmMemory;g.global={NaN:NaN,Infinity:Infinity};g["global.Math"]=Math;g.env=a;D++;d.monitorRunDependencies&&d.monitorRunDependencies(D);
if(d.instantiateWasm)try{return d.instantiateWasm(g,c)}catch(Xb){return d.printErr("Module.instantiateWasm callback failed with error: "+Xb),!1}d.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Na(f)||"function"!==typeof fetch?h(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),g).then(e).catch(function(a){d.printErr("wasm streaming compile failed: "+a);d.printErr("falling back to ArrayBuffer instantiation");h(e)});return{}}var e="asm-dom.wast",f="asm-dom.wasm",
h="asm-dom.temp.asm.js";"function"===typeof d.locateFile&&(Na(e)||(e=d.locateFile(e)),Na(f)||(f=d.locateFile(f)),Na(h)||(h=d.locateFile(h)));var g={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:d},k=null;d.asmPreload=d.asm;var l=d.reallocBuffer;d.reallocBuffer=function(a){if("asmjs"===m)var b=l(a);else a:{a=pa(a,d.usingWasm?65536:16777216);var c=d.buffer.byteLength;if(d.usingWasm)try{b=-1!==d.wasmMemory.grow((a-c)/65536)?d.buffer=d.wasmMemory.buffer:
null;break a}catch(C){b=null;break a}b=void 0}return b};var m="";d.asm=function(a,b){if(!b.table){a=d.wasmTableSize;void 0===a&&(a=1024);var e=d.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);d.wasmTable=b.table}b.memoryBase||(b.memoryBase=d.STATIC_BASE);b.tableBase||(b.tableBase=0);(b=c(b))||u("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");
return b}})();
var Oa=[function(a,b){window.asmDomHelpers.domApi.removeAttribute(a,d.UTF8ToString(b))},function(a,b,c){window.asmDomHelpers.domApi.setAttribute(a,d.UTF8ToString(b),d.UTF8ToString(c))},function(){return window.asmDomHelpers.domApi.createDocumentFragment()},function(a,b){return window.asmDomHelpers.domApi.createElementNS(d.UTF8ToString(a),d.UTF8ToString(b))},function(a){return window.asmDomHelpers.domApi.createElement(d.UTF8ToString(a))},function(a,b,c){window.asmDomHelpers.diff(a,b,c)},function(a,
b){window.asmDomHelpers.domApi.appendChild(a,b)},function(a){return window.asmDomHelpers.domApi.createTextNode(d.UTF8ToString(a))},function(a){return window.asmDomHelpers.domApi.createComment(d.UTF8ToString(a))},function(a,b,c){window.asmDomHelpers.domApi.insertBefore(a,b,window.asmDomHelpers.domApi.nextSibling(c))},function(a,b,c){window.asmDomHelpers.domApi.insertBefore(a,b,c)},function(a,b,c){window.asmDomHelpers.domApi.insertBefore(a,b,c)},function(a){window.asmDomHelpers.domApi.removeChild(a)},
function(a){a=window.asmDomHelpers.vnodesData[a];void 0!==a&&void 0!==a.ref&&a.ref(null)},function(a,b){window.asmDomHelpers.domApi.setNodeValue(a,d.UTF8ToString(b))},function(a,b){var c=window.asmDomHelpers.domApi.parentNode(b);0!==c&&(window.asmDomHelpers.domApi.insertBefore(c,a,window.asmDomHelpers.domApi.nextSibling(b)),window.asmDomHelpers.domApi.removeChild(b))}];va=1024;t=va+11696;Fa.push({C:function(){Pa()}},{C:function(){Qa()}},{C:function(){Ra()}},{C:function(){Sa()}});d.STATIC_BASE=va;
d.STATIC_BUMP=11696;var Ta=t;t+=16;function Ua(){return!!Ua.h}function Va(a){d.___errno_location&&(y[d.___errno_location()>>2]=a);return a}var E=0;function F(){E+=4;return y[E-4>>2]}var Wa={};
function G(a,b){E=b;try{var c=F(),e=F(),f=F();a=0;G.h||(G.h=[null,[],[]],G.P=function(a,b){var c=G.h[a];assert(c);0===b||10===b?((1===a?d.print:d.printErr)(oa(c,0)),c.length=0):c.push(b)});for(b=0;b<f;b++){for(var h=y[e+8*b>>2],g=y[e+(8*b+4)>>2],k=0;k<g;k++)G.P(c,v[h+k]);a+=g}return a}catch(l){return"undefined"!==typeof FS&&l instanceof FS.G||u(l),-l.I}}
var H=[8,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,7,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,
0,3,0,1,0,2,0,1,0],I=void 0,Xa,Za;"number"===typeof H?(Xa=!0,Za=H):(Xa=!1,Za=H.length);var J;J=ha(Math.max(Za,1));if(Xa){var $a;I=J;assert(0==(J&3));for($a=J+(Za&-4);I<$a;I+=4)y[I>>2]=0;for($a=J+Za;I<$a;)x[I++>>0]=0}else H.subarray||H.slice?v.set(H,J):v.set(new Uint8Array(H),J);function ab(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var bb=void 0;function K(a){for(var b="";v[a];)b+=bb[v[a++]];return b}
var L={},M={},cb={};function db(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function eb(a,b){a=db(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function fb(a){var b=Error,c=eb(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var N=void 0;function O(a){throw new N(a);}var gb=void 0;function hb(a){throw new gb(a);}
function P(a,b,c){function e(b){b=c(b);b.length!==a.length&&hb("Mismatched type converter count");for(var e=0;e<a.length;++e)Q(a[e],b[e])}a.forEach(function(a){cb[a]=b});var f=Array(b.length),h=[],g=0;b.forEach(function(a,b){M.hasOwnProperty(a)?f[b]=M[a]:(h.push(a),L.hasOwnProperty(a)||(L[a]=[]),L[a].push(function(){f[b]=M[a];++g;g===h.length&&e(f)}))});0===h.length&&e(f)}
function Q(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||O('type "'+e+'" must have a positive integer typeid pointer');if(M.hasOwnProperty(a)){if(c.X)return;O("Cannot register type '"+e+"' twice")}M[a]=b;delete cb[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(function(a){a()}))}function ib(a){O(a.a.f.b.name+" instance already deleted")}var jb=void 0,kb=[];
function lb(){for(;kb.length;){var a=kb.pop();a.a.u=!1;a["delete"]()}}function R(){}var mb={};function nb(a,b,c){if(void 0===a[b].g){var e=a[b];a[b]=function(){a[b].g.hasOwnProperty(arguments.length)||O("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].g+")!");return a[b].g[arguments.length].apply(this,arguments)};a[b].g=[];a[b].g[e.B]=e}}
function ob(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].g&&void 0!==d[a].g[c])&&O("Cannot register public name '"+a+"' twice"),nb(d,a,a),d.hasOwnProperty(c)&&O("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].g[c]=b):(d[a]=b,void 0!==c&&(d[a].na=c))}function pb(a,b,c,e,f,h,g,k){this.name=a;this.constructor=b;this.v=c;this.s=e;this.l=f;this.T=h;this.A=g;this.S=k;this.aa=[]}
function qb(a,b,c){for(;b!==c;)b.A||O("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.A(a),b=b.l;return a}function rb(a,b){if(null===b)return this.J&&O("null is not a valid "+this.name),0;b.a||O('Cannot pass "'+S(b)+'" as a '+this.name);b.a.c||O("Cannot pass deleted object as a pointer of type "+this.name);return qb(b.a.c,b.a.f.b,this.b)}
function sb(a,b){if(null===b){this.J&&O("null is not a valid "+this.name);if(this.F){var c=this.ba();null!==a&&a.push(this.s,c);return c}return 0}b.a||O('Cannot pass "'+S(b)+'" as a '+this.name);b.a.c||O("Cannot pass deleted object as a pointer of type "+this.name);!this.D&&b.a.f.D&&O("Cannot convert argument of type "+(b.a.j?b.a.j.name:b.a.f.name)+" to parameter type "+this.name);c=qb(b.a.c,b.a.f.b,this.b);if(this.F)switch(void 0===b.a.i&&O("Passing raw pointer to smart pointer is illegal"),this.ea){case 0:b.a.j===
this?c=b.a.i:O("Cannot convert argument of type "+(b.a.j?b.a.j.name:b.a.f.name)+" to parameter type "+this.name);break;case 1:c=b.a.i;break;case 2:if(b.a.j===this)c=b.a.i;else{var e=b.clone();c=this.da(c,T(function(){e["delete"]()}));null!==a&&a.push(this.s,c)}break;default:O("Unsupporting sharing policy")}return c}
function tb(a,b){if(null===b)return this.J&&O("null is not a valid "+this.name),0;b.a||O('Cannot pass "'+S(b)+'" as a '+this.name);b.a.c||O("Cannot pass deleted object as a pointer of type "+this.name);b.a.f.D&&O("Cannot convert argument of type "+b.a.f.name+" to parameter type "+this.name);return qb(b.a.c,b.a.f.b,this.b)}function ub(a){return this.fromWireType(z[a>>2])}function vb(a,b,c){if(b===c)return a;if(void 0===c.l)return null;a=vb(a,b,c.l);return null===a?null:c.S(a)}var wb={};
function xb(a,b){for(void 0===b&&O("ptr should not be undefined");a.l;)b=a.A(b),a=a.l;return wb[b]}function yb(a,b){b.f&&b.c||hb("makeClassHandle requires ptr and ptrType");!!b.j!==!!b.i&&hb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Object.create(a,{a:{value:b}})}
function U(a,b,c,e,f,h,g,k,l,m,p){this.name=a;this.b=b;this.J=c;this.D=e;this.F=f;this.$=h;this.ea=g;this.M=k;this.ba=l;this.da=m;this.s=p;f||void 0!==b.l?this.toWireType=sb:(this.toWireType=e?rb:tb,this.m=null)}function zb(a,b,c){d.hasOwnProperty(a)||hb("Replacing nonexistant public symbol");void 0!==d[a].g&&void 0!==c?d[a].g[c]=b:(d[a]=b,d[a].B=c)}
function V(a,b){a=K(a);if(void 0!==d["FUNCTION_TABLE_"+a])var c=d["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=d.asm["dynCall_"+a];void 0===c&&(c=d.asm["dynCall_"+a.replace(/f/g,"d")],void 0===c&&O("No dynCall invoker for signature: "+a));for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall",
"rawFunction",f+"};\n"))(c,b)}"function"!==typeof c&&O("unknown function pointer with signature "+a+": "+b);return c}var Ab=void 0;function Bb(a){a=Cb(a);var b=K(a);W(a);return b}function Db(a,b){function c(a){f[a]||M[a]||(cb[a]?cb[a].forEach(c):(e.push(a),f[a]=!0))}var e=[],f={};b.forEach(c);throw new Ab(a+": "+e.map(Bb).join([", "]));}function Eb(a,b){for(var c=[],e=0;e<a;e++)c.push(y[(b>>2)+e]);return c}function Fb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Gb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=eb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Hb(a,b,c,e,f){var h=b.length;2>h&&O("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].m){k=!0;break}var l="void"!==b[0].name,m="",p="";for(c=0;c<h-2;++c)m+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+db(a)+"("+m+") {\nif (arguments.length !== "+(h-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(h-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var w=k?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");e=[O,e,f,Fb,b[0],b[1]];g&&(a+="var thisWired = classParam.toWireType("+w+", this);\n");for(c=0;c<h-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+w+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),e.push(b[c+2]);g&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(l?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=g?1:2;c<b.length;++c)h=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].m&&(a+=h+"_dtor("+h+"); // "+b[c].name+"\n",m.push(h+"_dtor"),e.push(b[c].m));l&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return Gb(m).apply(null,e)}var Ib=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Jb(a){4<a&&0===--X[a].K&&(X[a]=void 0,Ib.push(a))}
function T(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ib.length?Ib.pop():X.length;X[b]={K:1,value:a};return b}}function S(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Kb(a,b){switch(b){case 2:return function(a){return this.fromWireType(sa[a>>2])};case 3:return function(a){return this.fromWireType(ta[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Lb(a,b,c){switch(b){case 0:return c?function(a){return x[a]}:function(a){return v[a]};case 1:return c?function(a){return qa[a>>1]}:function(a){return ra[a>>1]};case 2:return c?function(a){return y[a>>2]}:function(a){return z[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Mb(a){a||O("Cannot use deleted val. handle = "+a);return X[a].value}function Nb(a,b){var c=M[a];void 0===c&&O(b+" has unknown type "+Bb(a));return c}var Ob={};
function Pb(a){var b=Ob[a];return void 0===b?K(a):b}var Qb=[];function Rb(a){var b=Qb.length;Qb.push(a);return b}function Sb(a,b){for(var c=Array(a),e=0;e<a;++e)c[e]=Nb(y[(b>>2)+e],"parameter "+e);return c}var Tb=t;t+=16;var Ub,Y={};
function Vb(a){if(0===a)return 0;a=la(a);if(!Y.hasOwnProperty(a))return 0;Vb.h&&W(Vb.h);a=Y[a];for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}var f=b+1;if(b=Wb(f))if(c=b,e=x,0<f){f=c+f-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);55296<=g&&57343>=g&&(g=65536+((g&1023)<<10)|a.charCodeAt(++h)&1023);if(127>=g){if(c>=f)break;e[c++]=g}else{if(2047>=
g){if(c+1>=f)break;e[c++]=192|g>>6}else{if(65535>=g){if(c+2>=f)break;e[c++]=224|g>>12}else{if(2097151>=g){if(c+3>=f)break;e[c++]=240|g>>18}else{if(67108863>=g){if(c+4>=f)break;e[c++]=248|g>>24}else{if(c+5>=f)break;e[c++]=252|g>>30;e[c++]=128|g>>24&63}e[c++]=128|g>>18&63}e[c++]=128|g>>12&63}e[c++]=128|g>>6&63}e[c++]=128|g&63}}e[c]=0}Vb.h=b;return Vb.h}var Yb={},Zb=1;function $b(a,b){$b.h||($b.h={});a in $b.h||(d.dynCall_v(b),$b.h[a]=1)}for(var ac=Array(256),bc=0;256>bc;++bc)ac[bc]=String.fromCharCode(bc);
bb=ac;N=d.BindingError=fb("BindingError");gb=d.InternalError=fb("InternalError");R.prototype.isAliasOf=function(a){if(!(this instanceof R&&a instanceof R))return!1;var b=this.a.f.b,c=this.a.c,e=a.a.f.b;for(a=a.a.c;b.l;)c=b.A(c),b=b.l;for(;e.l;)a=e.A(a),e=e.l;return b===e&&c===a};
R.prototype.clone=function(){this.a.c||ib(this);if(this.a.w)return this.a.count.value+=1,this;var a=this.a;a=Object.create(Object.getPrototypeOf(this),{a:{value:{count:a.count,u:a.u,w:a.w,c:a.c,f:a.f,i:a.i,j:a.j}}});a.a.count.value+=1;a.a.u=!1;return a};R.prototype["delete"]=function(){this.a.c||ib(this);this.a.u&&!this.a.w&&O("Object already scheduled for deletion");--this.a.count.value;if(0===this.a.count.value){var a=this.a;a.i?a.j.s(a.i):a.f.b.s(a.c)}this.a.w||(this.a.i=void 0,this.a.c=void 0)};
R.prototype.isDeleted=function(){return!this.a.c};R.prototype.deleteLater=function(){this.a.c||ib(this);this.a.u&&!this.a.w&&O("Object already scheduled for deletion");kb.push(this);1===kb.length&&jb&&jb(lb);this.a.u=!0;return this};U.prototype.U=function(a){this.M&&(a=this.M(a));return a};U.prototype.L=function(a){this.s&&this.s(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=ub;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.F?yb(this.b.v,{f:this.$,c:c,j:this,i:a}):yb(this.b.v,{f:this,c:a})}var c=this.U(a);if(!c)return this.L(a),null;var e=xb(this.b,c);if(void 0!==e){if(0===e.a.count.value)return e.a.c=c,e.a.i=a,e.clone();e=e.clone();this.L(a);return e}e=this.b.T(c);e=mb[e];if(!e)return b.call(this);e=this.D?e.R:e.pointerType;var f=vb(c,this.b,e.b);return null===f?b.call(this):this.F?yb(e.b.v,{f:e,c:f,j:this,i:a}):yb(e.b.v,{f:e,c:f})};
d.getInheritedInstanceCount=function(){return Object.keys(wb).length};d.getLiveInheritedInstances=function(){var a=[],b;for(b in wb)wb.hasOwnProperty(b)&&a.push(wb[b]);return a};d.flushPendingDeletes=lb;d.setDelayFunction=function(a){jb=a;kb.length&&jb&&jb(lb)};Ab=d.UnboundTypeError=fb("UnboundTypeError");d.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
var cc,Z;Ub?(Z=y[Tb>>2],cc=y[Z>>2]):(Ub=!0,Y.USER=Y.LOGNAME="web_user",Y.PATH="/",Y.PWD="/",Y.HOME="/home/web_user",Y.LANG="C.UTF-8",Y._=d.thisProgram,cc=ha(1024),Z=ha(256),y[Z>>2]=cc,y[Tb>>2]=Z);var dc=[],ec=0,fc;for(fc in Y)if("string"===typeof Y[fc]){var hc=fc+"="+Y[fc];dc.push(hc);ec+=hc.length}if(1024<ec)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");
for(var ic=0;ic<dc.length;ic++){for(var jc=hc=dc[ic],kc=cc,lc=0;lc<jc.length;++lc)x[kc++>>0]=jc.charCodeAt(lc);x[kc>>0]=0;y[Z+4*ic>>2]=cc;cc+=hc.length+1}y[Z+4*dc.length>>2]=0;A=ha(4);wa=xa=ja(t);ya=wa+Ca;za=ja(ya);y[A>>2]=za;ia=!0;d.wasmTableSize=176;d.wasmMaxTableSize=176;d.N={};
d.O={abort:u,enlargeMemory:function(){var a=d.usingWasm?65536:16777216,b=2147483648-a;if(y[A>>2]>b)return!1;var c=B;for(B=Math.max(B,16777216);B<y[A>>2];)536870912>=B?B=pa(2*B,a):B=Math.min(pa((3*B+2147483648)/4,a),b);a=d.reallocBuffer(B);if(!a||a.byteLength!=B)return B=c,!1;d.buffer=buffer=a;ua();return!0},getTotalMemory:function(){return B},abortOnCannotGrowMemory:function(){u("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+B+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
___cxa_allocate_exception:function(a){return Wb(a)},___cxa_throw:function(a){"uncaught_exception"in Ua?Ua.h++:Ua.h=1;throw a;},___lock:function(){},___map_file:function(){Va(1);return-1},___setErrNo:Va,___syscall140:function(a,b){E=b;try{var c=Wa.V();F();var e=F(),f=F(),h=F();FS.ka(c,e,h);y[f>>2]=c.position;c.W&&0===e&&0===h&&(c.W=null);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.G||u(g),-g.I}},___syscall146:G,___syscall6:function(a,b){E=b;try{var c=Wa.V();FS.close(c);return 0}catch(e){return"undefined"!==
typeof FS&&e instanceof FS.G||u(e),-e.I}},___syscall91:function(a,b){E=b;try{var c=F(),e=F(),f=Wa.Z[c];if(!f)return 0;if(e===f.ja){var h=FS.ia(f.fd);Wa.ha(c,h,e,f.flags);FS.ma(h);Wa.Z[c]=null;f.ga&&W(f.la)}return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.G||u(g),-g.I}},___unlock:function(){},__embind_register_bool:function(a,b,c,e,f){var h=ab(c);b=K(b);Q(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===
c)var e=x;else if(2===c)e=qa;else if(4===c)e=y;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>h])},m:null})},__embind_register_class:function(a,b,c,e,f,h,g,k,l,m,p,w,Ya){p=K(p);h=V(f,h);k&&(k=V(g,k));m&&(m=V(l,m));Ya=V(w,Ya);var C=db(p);ob(C,function(){Db("Cannot construct "+p+" due to unbound types",[e])});P([a,b,c],e?[e]:[],function(b){b=b[0];if(e){var c=b.b;var f=c.v}else f=R.prototype;b=eb(C,function(){if(Object.getPrototypeOf(this)!==g)throw new N("Use 'new' to construct "+
p);if(void 0===l.o)throw new N(p+" has no accessible constructor");var a=l.o[arguments.length];if(void 0===a)throw new N("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(l.o).toString()+") parameters instead!");return a.apply(this,arguments)});var g=Object.create(f,{constructor:{value:b}});b.prototype=g;var l=new pb(p,b,g,Ya,c,h,k,m);c=new U(p,l,!0,!1,!1);f=new U(p+"*",l,!1,!1,!1);var w=new U(p+" const*",l,!1,!0,!1);mb[a]={pointerType:f,
R:w};zb(C,b);return[c,f,w]})},__embind_register_class_constructor:function(a,b,c,e,f,h){var g=Eb(b,c);f=V(e,f);P([],[a],function(a){a=a[0];var c="constructor "+a.name;void 0===a.b.o&&(a.b.o=[]);if(void 0!==a.b.o[b-1])throw new N("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");a.b.o[b-1]=function(){Db("Cannot construct "+a.name+" due to unbound types",
g)};P([],g,function(e){a.b.o[b-1]=function(){arguments.length!==b-1&&O(c+" called with "+arguments.length+" arguments, expected "+(b-1));var a=[],g=Array(b);g[0]=h;for(var k=1;k<b;++k)g[k]=e[k].toWireType(a,arguments[k-1]);g=f.apply(null,g);Fb(a);return e[0].fromWireType(g)};return[]});return[]})},__embind_register_class_function:function(a,b,c,e,f,h,g,k){var l=Eb(c,e);b=K(b);h=V(f,h);P([],[a],function(a){function e(){Db("Cannot call "+f+" due to unbound types",l)}a=a[0];var f=a.name+"."+b;k&&a.b.aa.push(b);
var m=a.b.v,C=m[b];void 0===C||void 0===C.g&&C.className!==a.name&&C.B===c-2?(e.B=c-2,e.className=a.name,m[b]=e):(nb(m,b,f),m[b].g[c-2]=e);P([],l,function(e){e=Hb(f,e,a,h,g);void 0===m[b].g?(e.B=c-2,m[b]=e):m[b].g[c-2]=e;return[]});return[]})},__embind_register_emval:function(a,b){b=K(b);Q(a,{name:b,fromWireType:function(a){var b=X[a].value;Jb(a);return b},toWireType:function(a,b){return T(b)},argPackAdvance:8,readValueFromPointer:ub,m:null})},__embind_register_float:function(a,b,c){c=ab(c);b=K(b);
Q(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+S(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Kb(b,c),m:null})},__embind_register_function:function(a,b,c,e,f,h){var g=Eb(b,c);a=K(a);f=V(e,f);ob(a,function(){Db("Cannot call "+a+" due to unbound types",g)},b-1);P([],g,function(c){c=[c[0],null].concat(c.slice(1));zb(a,Hb(a,c,null,f,h),b-1);return[]})},__embind_register_integer:function(a,
b,c,e,f){function h(a){return a}b=K(b);-1===f&&(f=4294967295);var g=ab(c);if(0===e){var k=32-8*c;h=function(a){return a<<k>>>k}}var l=-1!=b.indexOf("unsigned");Q(a,{name:b,fromWireType:h,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+S(c)+'" to '+this.name);if(c<e||c>f)throw new TypeError('Passing a number "'+S(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return l?c>>>
0:c|0},argPackAdvance:8,readValueFromPointer:Lb(b,g,0!==e),m:null})},__embind_register_memory_view:function(a,b,c){function e(a){a>>=2;var b=z;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=K(c);Q(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{X:!0})},__embind_register_std_string:function(a,b){b=K(b);Q(a,{name:b,fromWireType:function(a){for(var b=z[a>>2],c=Array(b),h=0;h<b;++h)c[h]=String.fromCharCode(v[a+
4+h]);W(a);return c.join("")},toWireType:function(a,b){function c(a,b){return a[b]}function e(a,b){return a.charCodeAt(b)}b instanceof ArrayBuffer&&(b=new Uint8Array(b));var g;b instanceof Uint8Array?g=c:b instanceof Uint8ClampedArray?g=c:b instanceof Int8Array?g=c:"string"===typeof b?g=e:O("Cannot pass non-string to std::string");var k=b.length,l=Wb(4+k);z[l>>2]=k;for(var m=0;m<k;++m){var p=g(b,m);255<p&&(W(l),O("String has UTF-16 code units that do not fit in 8 bits"));v[l+4+m]=p}null!==a&&a.push(W,
l);return l},argPackAdvance:8,readValueFromPointer:ub,m:function(a){W(a)}})},__embind_register_std_wstring:function(a,b,c){c=K(c);if(2===b){var e=function(){return ra};var f=1}else 4===b&&(e=function(){return z},f=2);Q(a,{name:c,fromWireType:function(a){for(var b=e(),c=z[a>>2],h=Array(c),m=a+4>>f,p=0;p<c;++p)h[p]=String.fromCharCode(b[m+p]);W(a);return h.join("")},toWireType:function(a,c){var g=e(),h=c.length,m=Wb(4+h*b);z[m>>2]=h;for(var p=m+4>>f,w=0;w<h;++w)g[p+w]=c.charCodeAt(w);null!==a&&a.push(W,
m);return m},argPackAdvance:8,readValueFromPointer:ub,m:function(a){W(a)}})},__embind_register_void:function(a,b){b=K(b);Q(a,{Y:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},__emval_as:function(a,b,c){a=Mb(a);b=Nb(b,"emval::as");var e=[],f=T(e);y[c>>2]=f;return b.toWireType(e,a)},__emval_call_method:function(a,b,c,e,f){a=Qb[a];b=Mb(b);c=Pb(c);var h=[];y[e>>2]=T(h);return a(b,c,h,f)},__emval_decref:Jb,__emval_get_global:function(a){if(0===a)return T(Function("return this")());
a=Pb(a);return T(Function("return this")()[a])},__emval_get_method_caller:function(a,b){b=Sb(a,b);for(var c=b[0],e=c.name+"_$"+b.slice(1).map(function(a){return a.name}).join("_")+"$",f=["retType"],h=[c],g="",k=0;k<a-1;++k)g+=(0!==k?", ":"")+"arg"+k,f.push("argType"+k),h.push(b[1+k]);e="return function "+db("methodCaller_"+e)+"(handle, name, destructors, args) {\n";var l=0;for(k=0;k<a-1;++k)e+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(l?"+"+l:"")+");\n",l+=b[k+1].argPackAdvance;
e+="    var rv = handle[name]("+g+");\n";for(k=0;k<a-1;++k)b[k+1].deleteObject&&(e+="    argType"+k+".deleteObject(arg"+k+");\n");c.Y||(e+="    return retType.toWireType(destructors, rv);\n");f.push(e+"};\n");a=Gb(f).apply(null,h);return Rb(a)},__emval_get_property:function(a,b){a=Mb(a);b=Mb(b);return T(a[b])},__emval_incref:function(a){4<a&&(X[a].K+=1)},__emval_new_cstring:function(a){return T(Pb(a))},__emval_run_destructors:function(a){Fb(X[a].value);Jb(a)},__emval_take_value:function(a,b){a=Nb(a,
"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},_abort:function(){d.abort()},_emscripten_asm_const_i:function(a){return Oa[a]()},_emscripten_asm_const_ii:function(a,b){return Oa[a](b)},_emscripten_asm_const_iii:function(a,b,c){return Oa[a](b,c)},_emscripten_asm_const_iiii:function(a,b,c,e){return Oa[a](b,c,e)},_emscripten_memcpy_big:function(a,b,c){v.set(v.subarray(b,b+c),a);return a},_getenv:Vb,_pthread_getspecific:function(a){return Yb[a]||0},_pthread_key_create:function(a){if(0==
a)return 22;y[a>>2]=Zb;Yb[Zb]=0;Zb++;return 0},_pthread_once:$b,_pthread_setspecific:function(a,b){if(!(a in Yb))return 22;Yb[a]=b;return 0},DYNAMICTOP_PTR:A,tempDoublePtr:Ta,STACKTOP:xa};var mc=d.asm(d.N,d.O,buffer);d.asm=mc;
var Pa=d.__GLOBAL__sub_I_asm_dom_cpp=function(){return d.asm.__GLOBAL__sub_I_asm_dom_cpp.apply(null,arguments)},Qa=d.__GLOBAL__sub_I_asm_dom_server_cpp=function(){return d.asm.__GLOBAL__sub_I_asm_dom_server_cpp.apply(null,arguments)},Sa=d.__GLOBAL__sub_I_bind_cpp=function(){return d.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)},Ra=d.__GLOBAL__sub_I_index_cpp=function(){return d.asm.__GLOBAL__sub_I_index_cpp.apply(null,arguments)},Cb=d.___getTypeName=function(){return d.asm.___getTypeName.apply(null,
arguments)},Aa=d._emscripten_replace_memory=function(){return d.asm._emscripten_replace_memory.apply(null,arguments)},W=d._free=function(){return d.asm._free.apply(null,arguments)},Wb=d._malloc=function(){return d.asm._malloc.apply(null,arguments)};d.stackAlloc=function(){return d.asm.stackAlloc.apply(null,arguments)};d.dynCall_i=function(){return d.asm.dynCall_i.apply(null,arguments)};d.dynCall_ii=function(){return d.asm.dynCall_ii.apply(null,arguments)};
d.dynCall_iii=function(){return d.asm.dynCall_iii.apply(null,arguments)};d.dynCall_iiii=function(){return d.asm.dynCall_iiii.apply(null,arguments)};d.dynCall_iiiii=function(){return d.asm.dynCall_iiiii.apply(null,arguments)};d.dynCall_iiiiii=function(){return d.asm.dynCall_iiiiii.apply(null,arguments)};d.dynCall_iiiiiiiii=function(){return d.asm.dynCall_iiiiiiiii.apply(null,arguments)};d.dynCall_v=function(){return d.asm.dynCall_v.apply(null,arguments)};
d.dynCall_vi=function(){return d.asm.dynCall_vi.apply(null,arguments)};d.dynCall_vii=function(){return d.asm.dynCall_vii.apply(null,arguments)};d.dynCall_viii=function(){return d.asm.dynCall_viii.apply(null,arguments)};d.dynCall_viiii=function(){return d.asm.dynCall_viiii.apply(null,arguments)};d.dynCall_viiiii=function(){return d.asm.dynCall_viiiii.apply(null,arguments)};d.dynCall_viiiiii=function(){return d.asm.dynCall_viiiiii.apply(null,arguments)};d.asm=mc;d.UTF8ToString=ma;
d.then=function(a){if(d.calledRun)a(d);else{var b=d.onRuntimeInitialized;d.onRuntimeInitialized=function(){b&&b();a(d)}}return d};function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}fa.prototype=Error();fa.prototype.constructor=fa;Ma=function nc(){d.calledRun||oc();d.calledRun||(Ma=nc)};
function oc(){function a(){if(!d.calledRun&&(d.calledRun=!0,!ka)){Ja||(Ja=!0,Da(Fa));Da(Ga);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var a=d.postRun.shift();Ia.unshift(a)}Da(Ia)}}if(!(0<D)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ka();Da(Ea);0<D||d.calledRun||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},
1);a()},1)):a())}}d.run=oc;d.exit=function(a,b){if(!b||!d.noExitRuntime||0!==a){if(!d.noExitRuntime&&(ka=!0,xa=void 0,Da(Ha),d.onExit))d.onExit(a);ba&&process.exit(a);d.quit(a,new fa(a))}};function u(a){if(d.onAbort)d.onAbort(a);void 0!==a?(d.print(a),d.printErr(a),a=JSON.stringify(a)):a="";ka=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}d.abort=u;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();d.noExitRuntime=!0;oc();


  return Module;
};
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
